# Generated by Django 5.2.6 on 2025-10-02 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('item_type', models.CharField(max_length=50)),
                ('serial_number', models.CharField(max_length=50, unique=True)),
                ('condition', models.CharField(choices=[('Available', 'Available'), ('Borrowed', 'Borrowed'), ('Under Maintenance', 'Under Maintenance'), ('Lost', 'Lost')], default='Available', max_length=20)),
            ],
        ),
    ]
