# Generated by Django 5.2.6 on 2025-10-03 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_profile_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowtransaction',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
