# Generated by Django 5.2.6 on 2025-10-03 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_borrowtransaction_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowtransaction',
            name='borrow_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
