# Generated by Django 5.2.6 on 2025-11-25 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_borrowtransaction_borrow_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowtransaction',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Rejected', 'Rejected'), ('Borrowed', 'Borrowed'), ('Returned', 'Returned'), ('Overdue', 'Overdue')], default='Pending', max_length=20),
        ),
    ]
